(define (problem basic) (:domain reserves)
  (:objects
    habitacio0 - habitacio
    habitacio1 - habitacio
    habitacio2 - habitacio
    habitacio3 - habitacio
    reserva0 - reserva
    reserva1 - reserva
    reserva2 - reserva
    dia0 - dia
    dia1 - dia
    dia2 - dia
    dia3 - dia
    dia4 - dia
    dia5 - dia
    dia6 - dia
    dia7 - dia
    dia8 - dia
    dia9 - dia
    dia10 - dia
    dia11 - dia
    dia12 - dia
    dia13 - dia
    dia14 - dia
    dia15 - dia
    dia16 - dia
    dia17 - dia
    dia18 - dia
    dia19 - dia
    dia20 - dia
    dia21 - dia
    dia22 - dia
    dia23 - dia
    dia24 - dia
    dia25 - dia
    dia26 - dia
    dia27 - dia
    dia28 - dia
    dia29 - dia
  )
  (:init
    (lliure habitacio0 dia0)
    (lliure habitacio0 dia1)
    (lliure habitacio0 dia2)
    (lliure habitacio0 dia3)
    (lliure habitacio0 dia4)
    (lliure habitacio0 dia5)
    (lliure habitacio0 dia6)
    (lliure habitacio0 dia7)
    (lliure habitacio0 dia8)
    (lliure habitacio0 dia9)
    (lliure habitacio0 dia10)
    (lliure habitacio0 dia11)
    (lliure habitacio0 dia12)
    (lliure habitacio0 dia13)
    (lliure habitacio0 dia14)
    (lliure habitacio0 dia15)
    (lliure habitacio0 dia16)
    (lliure habitacio0 dia17)
    (lliure habitacio0 dia18)
    (lliure habitacio0 dia19)
    (lliure habitacio0 dia20)
    (lliure habitacio0 dia21)
    (lliure habitacio0 dia22)
    (lliure habitacio0 dia23)
    (lliure habitacio0 dia24)
    (lliure habitacio0 dia25)
    (lliure habitacio0 dia26)
    (lliure habitacio0 dia27)
    (lliure habitacio0 dia28)
    (lliure habitacio0 dia29)
    (lliure habitacio1 dia0)
    (lliure habitacio1 dia1)
    (lliure habitacio1 dia2)
    (lliure habitacio1 dia3)
    (lliure habitacio1 dia4)
    (lliure habitacio1 dia5)
    (lliure habitacio1 dia6)
    (lliure habitacio1 dia7)
    (lliure habitacio1 dia8)
    (lliure habitacio1 dia9)
    (lliure habitacio1 dia10)
    (lliure habitacio1 dia11)
    (lliure habitacio1 dia12)
    (lliure habitacio1 dia13)
    (lliure habitacio1 dia14)
    (lliure habitacio1 dia15)
    (lliure habitacio1 dia16)
    (lliure habitacio1 dia17)
    (lliure habitacio1 dia18)
    (lliure habitacio1 dia19)
    (lliure habitacio1 dia20)
    (lliure habitacio1 dia21)
    (lliure habitacio1 dia22)
    (lliure habitacio1 dia23)
    (lliure habitacio1 dia24)
    (lliure habitacio1 dia25)
    (lliure habitacio1 dia26)
    (lliure habitacio1 dia27)
    (lliure habitacio1 dia28)
    (lliure habitacio1 dia29)
    (lliure habitacio2 dia0)
    (lliure habitacio2 dia1)
    (lliure habitacio2 dia2)
    (lliure habitacio2 dia3)
    (lliure habitacio2 dia4)
    (lliure habitacio2 dia5)
    (lliure habitacio2 dia6)
    (lliure habitacio2 dia7)
    (lliure habitacio2 dia8)
    (lliure habitacio2 dia9)
    (lliure habitacio2 dia10)
    (lliure habitacio2 dia11)
    (lliure habitacio2 dia12)
    (lliure habitacio2 dia13)
    (lliure habitacio2 dia14)
    (lliure habitacio2 dia15)
    (lliure habitacio2 dia16)
    (lliure habitacio2 dia17)
    (lliure habitacio2 dia18)
    (lliure habitacio2 dia19)
    (lliure habitacio2 dia20)
    (lliure habitacio2 dia21)
    (lliure habitacio2 dia22)
    (lliure habitacio2 dia23)
    (lliure habitacio2 dia24)
    (lliure habitacio2 dia25)
    (lliure habitacio2 dia26)
    (lliure habitacio2 dia27)
    (lliure habitacio2 dia28)
    (lliure habitacio2 dia29)
    (lliure habitacio3 dia0)
    (lliure habitacio3 dia1)
    (lliure habitacio3 dia2)
    (lliure habitacio3 dia3)
    (lliure habitacio3 dia4)
    (lliure habitacio3 dia5)
    (lliure habitacio3 dia6)
    (lliure habitacio3 dia7)
    (lliure habitacio3 dia8)
    (lliure habitacio3 dia9)
    (lliure habitacio3 dia10)
    (lliure habitacio3 dia11)
    (lliure habitacio3 dia12)
    (lliure habitacio3 dia13)
    (lliure habitacio3 dia14)
    (lliure habitacio3 dia15)
    (lliure habitacio3 dia16)
    (lliure habitacio3 dia17)
    (lliure habitacio3 dia18)
    (lliure habitacio3 dia19)
    (lliure habitacio3 dia20)
    (lliure habitacio3 dia21)
    (lliure habitacio3 dia22)
    (lliure habitacio3 dia23)
    (lliure habitacio3 dia24)
    (lliure habitacio3 dia25)
    (lliure habitacio3 dia26)
    (lliure habitacio3 dia27)
    (lliure habitacio3 dia28)
    (lliure habitacio3 dia29)
    (reservada reserva0 dia11)
    (reservada reserva0 dia12)
    (reservada reserva1 dia11)
    (reservada reserva1 dia12)
    (reservada reserva1 dia13)
    (reservada reserva1 dia14)
    (reservada reserva1 dia15)
    (reservada reserva1 dia16)
    (reservada reserva1 dia17)
    (reservada reserva1 dia18)
    (reservada reserva1 dia19)
    (reservada reserva1 dia20)
    (reservada reserva2 dia27)
    (reservada reserva2 dia28)
    (reservada reserva2 dia29)
    (= (capacitat_habitacio habitacio0) 2)
    (= (capacitat_habitacio habitacio1) 3)
    (= (capacitat_habitacio habitacio2) 1)
    (= (capacitat_habitacio habitacio3) 4)
    (= (capacitat_reserva reserva0) 1)
    (= (capacitat_reserva reserva1) 2)
    (= (capacitat_reserva reserva2) 2)
  )
(:goal (forall (?reserva - reserva) (correcta ?reserva)))
)
